<div class="page-body">
<div class="row">
    <div class="col-xs-12 col-md-12">

        <div class="widget panel">
           <div class="filters" context="" define="">
                <ul class="filter-tab-list" id="filter-tab-list">

                        <li class="filter-tab-item" data-tab-index="1">
                            <a href="/admin/products" class="filter-tab filter-tab-active">Tất cả sản phẩm</a>
                        </li>
                                        

                    <li class="dropdown-container" id="hidden-search" style="display:none">
                        <a class="dropdown-toggle btn-hidden-search filter-tab" data-toggle="dropdown">
                            Xem thêm
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu arrow-style dropdown-hidden-search pull-right padding-sm" id="dropdown-hidden-search"></ul>
                    </li>

                </ul>

                <div class="filter-container">
                    <div class="btn-group btn-group-filter">
                        
                        <div class="search-container">
                            <input type="text" class="form-control form-large search-input" placeholder="Nhập từ khóa tìm kiếm ...(Tên sản phẩm, Tên variant, SKU, Tag)" bind="query" bind-event-change="submitQuery()" value="">
                        </div>
                    </div>
                    <div class="btn-group btn-group-filter">
                        <div class="btn-group">
                            <div class="bootstrap-tagsinput" style="border:0;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body  bulk-action-context">
            <div class="table-responsive">
                <table class=" table table-hover">
                  <thead>
                      <tr>
                      <th>Chưa rõ</th>
                      <th class="col-sm-4">Danh mục</th>
                    </tr>
                  </thead>
                  <tbody>
                      <tr>
                      <td><div class=" dd dd-draghandle darker col-sm-12">
  <ol class="dd-list">
    <li class="dd-item dd2-item" data-id="13">
      <div class="dd-handle dd2-handle">
        <i class="normal-icon fa fa-android"></i>

        <i class="drag-icon fa fa-arrows-alt "></i>
      </div>
      <div class="dd2-content">First Level</div>
    </li>

    <li class="dd-item dd2-item" data-id="14">
      <div class="dd-handle dd2-handle">
        <i class="normal-icon fa fa-facebook "></i>

        <i class="drag-icon fa fa-arrows-alt "></i>
      </div>
      <div class="dd2-content">Second Level</div>
    </li>

    <li class="dd-item dd2-item" data-id="15"><button data-action="collapse" type="button">Collapse</button><button data-action="expand" type="button" style="display: none;">Expand</button>
      <div class="dd-handle dd2-handle">
        <i class="normal-icon fa fa-twitter "></i>

        <i class="drag-icon fa fa-arrows-alt "></i>
      </div>
      <div class="dd2-content">Third Level</div>

      <ol class="dd-list" style="">
        <li class="dd-item dd2-item" data-id="16">
          <div class="dd-handle dd2-handle">
            <i class="normal-icon fa fa-google-plus "></i>

            <i class="drag-icon fa fa-arrows-alt "></i>
          </div>
          <div class="dd2-content">Sub Item 1</div>
        </li>

        <li class="dd-item dd2-item dd-colored" data-id="17">
          <div class="dd-handle dd2-handle bg-info">
            <i class="normal-icon fa fa-instagram"></i>

            <i class="drag-icon fa fa-arrows-alt "></i>
          </div>
          <div class="dd2-content bg-azure no-hover">Sub Item 2</div>
        </li>
        <li class="dd-item dd2-item" data-id="18">
          <div class="dd-handle dd2-handle">
            <i class="normal-icon fa fa-taxi"></i>
            <i class="drag-icon fa fa-arrows-alt"></i>
          </div>
          <div class="dd2-content">Sub Item 3</div>
        </li>
      </ol>
    </li>
  </ol>
</div>
                      </td>
                      <td><a href="">Bếp từ Faster</a></td>
                    </tr>
                     
                  </tbody>
            </table>
            </div>
            </div>
            </div>
        </div>
    </div>
</div>