<!DOCTYPE html>
<!--
BeyondAdmin - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.4
Version: 1.4
Purchase: http://wrapbootstrap.com
-->

<html xmlns="http://www.w3.org/1999/xhtml">
<!-- Head -->
<head>
    <meta charset="utf-8" />
    <title>Dashboard</title>

    <meta name="description" content="Dashboard" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="shortcut icon" href="<?php echo URL_TEMPLATE ?>/admin/assets/img/favicon.png" type="image/x-icon">


    <!--Basic Styles-->
    <?php 
    $linkCss 	= URL_TEMPLATE.'/admin/assets/css/';
    $linkJs		= URL_TEMPLATE.'/admin/assets/js/';
		echo $this->headLink()->appendStylesheet($linkCss.'bootstrap.min.css')
								->appendStylesheet($linkCss.'font-awesome.min.css')
								->appendStylesheet($linkCss.'weather-icons.min.css')
								->appendStylesheet($linkCss.'beyond.css')
								->appendStylesheet($linkCss.'demo.min.css')
								->appendStylesheet($linkCss.'typicons.min.css')
								->appendStylesheet($linkCss.'animate.min.css')
    	;
  
	?>

    <!--Fonts-->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>
    
    <!--Beyond styles-->
</head>
<!-- /Head -->
<!-- Body -->
<body>
    <!-- Navbar -->
    <?php include 'include/navbar.php'; ?>
    <!-- /Navbar -->
    <!-- Main Container -->
    <div class="main-container container-fluid">
        <!-- Page Container -->
        <div class="page-container">

            <!-- Page Sidebar -->
            	<?php include 'include/sidebar-left.php'; ?>
            <!-- /Page Sidebar -->
            <!-- Chat Bar -->
            <div id="chatbar" class="page-chatbar">
                <div class="chatbar-contacts">
                    <div class="contacts-search">
                        <input type="text" class="searchinput" placeholder="Search Contacts" />
                        <i class="searchicon fa fa-search"></i>
                        <div class="searchhelper">Search Your Contacts and Chat History</div>
                    </div>
                    <ul class="contacts-list">
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/divyia.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Divyia Philips</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    last week
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Nicolai-Larson.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Adam Johnson</div>
                                <div class="contact-status">
                                    <div class="offline"></div>
                                    <div class="status">left 4 mins ago</div>
                                </div>
                                <div class="last-chat-time">
                                    today
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/John-Smith.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">John Smith</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    1:57 am
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Osvaldus-Valutis.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Osvaldus Valutis</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    today
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Javi-Jimenez.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Javi Jimenez</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    today
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Stephanie-Walter.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Stephanie Walter</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    yesterday
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Sergey-Azovskiy.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Sergey Azovskiy</div>
                                <div class="contact-status">
                                    <div class="offline"></div>
                                    <div class="status">offline since oct 24</div>
                                </div>
                                <div class="last-chat-time">
                                    22 oct
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/Lee-Munroe.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Lee Munroe</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    today
                                </div>
                            </div>
                        </li>
                        <li class="contact">
                            <div class="contact-avatar">
                                <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/divyia.jpg" />
                            </div>
                            <div class="contact-info">
                                <div class="contact-name">Divyia Philips</div>
                                <div class="contact-status">
                                    <div class="online"></div>
                                    <div class="status">online</div>
                                </div>
                                <div class="last-chat-time">
                                    last week
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="chatbar-messages" style="display: none;">
                    <div class="messages-contact">
                        <div class="contact-avatar">
                            <img src="<?php echo URL_TEMPLATE ?>/admin/assets/img/avatars/divyia.jpg" />
                        </div>
                        <div class="contact-info">
                            <div class="contact-name">Divyia Philips</div>
                            <div class="contact-status">
                                <div class="online"></div>
                                <div class="status">online</div>
                            </div>
                            <div class="last-chat-time">
                                a moment ago
                            </div>
                            <div class="back">
                                <i class="fa fa-arrow-circle-left"></i>
                            </div>
                        </div>
                    </div>
                    <ul class="messages-list">
                        <li class="message">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Me</div>
                                <div class="message-time">10:14 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                        <li class="message reply">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Divyia</div>
                                <div class="message-time">10:15 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                        <li class="message">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Me</div>
                                <div class="message-time">10:14 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                        <li class="message reply">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Divyia</div>
                                <div class="message-time">10:15 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                        <li class="message">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Me</div>
                                <div class="message-time">10:14 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                        <li class="message reply">
                            <div class="message-info">
                                <div class="bullet"></div>
                                <div class="contact-name">Divyia</div>
                                <div class="message-time">10:15 AM, Today</div>
                            </div>
                            <div class="message-body">
                                Hi, Hope all is good. Are we meeting today?
                            </div>
                        </li>
                    </ul>
                    <div class="send-message">
                        <span class="input-icon icon-right">
                            <textarea rows="4" class="form-control" placeholder="Type your message"></textarea>
                            <i class="fa fa-camera themeprimary"></i>
                        </span>
                    </div>
                </div>
            </div>
            <!-- /Chat Bar -->
            <!-- Page Content -->
            <div class="page-content">
                <!-- Page Breadcrumb -->
                <?php
                    include 'include/breadcrumb.php';
                    echo $this->content;
                ?>
                <!-- /Page Breadcrumb -->
                <!-- /Page Header -->
                <!-- Page Body -->
                <?php  ?>
                </form>
                <!-- /Page Body -->
            </div>
            <!-- /Page Content -->

        </div>
        <!-- /Page Container -->
        <!-- Main Container -->

    </div>

    <?php
        echo $this->headScript()->appendFile($linkJs.'skins.min.js'); 

    	echo $this->headScript()->appendFile($linkJs.'jquery.min.js')
    							->appendFile($linkJs.'bootstrap.min.js')
    							->appendFile($linkJs.'slimscroll/jquery.slimscroll.min.js')
    							// <!--Beyond Scripts-->
    							->appendFile($linkJs.'beyond.js')
    							// <!--Page Related Scripts-->
    							// <!--Sparkline Charts Needed Scripts-->
    							->appendFile($linkJs.'charts/sparkline/jquery.sparkline.js')
    							->appendFile($linkJs.'charts/sparkline/sparkline-init.js')
    							/*<!--Easy Pie Charts Needed Scripts-->*/
    							->appendFile($linkJs.'charts/easypiechart/jquery.easypiechart.js')
    							->appendFile($linkJs.'charts/easypiechart/easypiechart-init.js')
    							/*<!--Flot Charts Needed Scripts-->*/
    							->appendFile($linkJs.'charts/flot/jquery.flot.js')
    							->appendFile($linkJs.'charts/flot/jquery.flot.resize.js')
    							->appendFile($linkJs.'charts/flot/jquery.flot.pie.js')
    							->appendFile($linkJs.'charts/flot/jquery.flot.tooltip.js')
    							->appendFile($linkJs.'charts/flot/jquery.flot.pie.js')
    							->appendFile($linkJs.'charts/flot/jquery.flot.orderBars.js')
                                ->appendFile($linkJs.'select2/select2.js')
    	; 
        if($this->action == 'add'){
            echo '<script type="text/javascript" src="/public/template/admin/assets/js/datetime/bootstrap-datepicker.js"></script>';

        }
    ?>
    <!-- FormValidation plugin -->
    <!-- FormValidation plugin and the class supports validating Bootstrap form -->

    
    <script src="/public/template/admin/assets/js/validation/bootstrapValidator.js"></script>
        <script type="text/javascript">
        // $(document).ready(function() {
        //     $('#validator').bootstrapValidator();
        // });
        </script>
        <script type="text/javascript">
        //--Jquery Select2--
        var inventory_policy = $('select[name = inventory_policy]').val();
        ShowOrHide(inventory_policy);
           $('select[name = inventory_policy]').on('change',function(){
                var ElementValue = $(this).val();
                if(ElementValue == 1){
                   emptyClass('#Quantity','hide')
                }else{
                   setClass('#Quantity','hide')
                }
           });
           function ShowOrHide(element){
                if(inventory_policy == 1){
                   emptyClass('#Quantity','hide')
                }else{
                   setClass('#Quantity','hide')
                }
           }
           $('#openImage').click(function(){
               var InputFile = $(this).attr('role');
               $('input[name=\''+InputFile+'\']').click();
           });
           $('#openAlbumImage').click(function(){
               var InputFile = $(this).attr('role');
               $('input[name=\''+InputFile+'\']').click();
           });
          
           function setClass($element,$class){
                $($element).addClass($class);
           }
           function emptyClass($element,$class){
                $($element).removeClass($class);
           }
           function hideElement($element){
                $($element).hide();
           }
           function showElement($element,$delay){
                $($element).show();
           };

           /*Check All*/
           
        </script> 
    <!-- Check All  -->
    <script type="text/javascript" src="/public/template/admin/assets/js/default.js"></script>
    <script type="text/javascript" src="/public/template/admin/assets/js/editors/ckeditor/ckeditor.js"></script>
	<script>
	    CKEDITOR.replace( 'ckeditor' );
	</script>
<div class="container-fluid-md notifications">
	<div class="ajax-notification">
		<span class="ajax-notification-message"></span><a
			class='close-notification'><i class='fa fa-times'></i></a>
	</div>
</div>
</body>
<!--  /Body -->
</html>
