<form method="post" action="">
<div class="page-body">
<div class="row">
    <div class="col-lg-12 col-sm-12 col-xs-12">
        <div class="row">
            <div class="col-lg-8 col-sm-6 col-xs-12"><div class="widget"><div class="widget-body"><div class="row">
                <div class="col-sm-9">
                    <?php
                    echo '<div class="form-group">
                                            '.$this->formLabel($_formObj->get('name')).'
                                            <div class="controls">
                                             '.$this->formInput($_formObj->get('name')).'
                                            </div>
                                      </div>';
                    ?>
                </div>
                 <div class="col-sm-3">
                    <?php
                    echo '<div class="form-group">
                                            '.$this->formLabel($_formObj->get('sort_order')).'
                                            <div class="controls">
                                             '.$this->formInput($_formObj->get('sort_order')).'
                                            </div>
                                      </div>';
                    ?>
                </div>
                <div class="col-sm-12">
                        <div class="table-responsive">
                        <table class=" table table-hover " id="filter">
                            <thead>
                                <tr>
                                  <th class="col-sm-9">Filter Name </th>
                                  <th class="col-sm-3">Sort order</th>
                                  <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="2"></td>
                                <td class="text-left"><a onclick="addFilterRow();" class="btn btn-primary" ><i class="fa fa-plus-circle"></i></a>
                                </td>
                            </tr>
                            <?php
                                $xHtml = '';
                                $filter_row = 0;
                                    
                                $xHtml .= '';
                                echo $xHtml;
                            ?>
                            
                            </tbody>
                    </table>
                    </div>
                </div>
            </div>
            </div>
            </div>
            </div>

            <div class="col-lg-4 col-sm-6 col-xs-12">
                <div class="widget">
                    <div class="widget-body">

                        <label class="title-product-main text-no-bold block-display text-center ">
                        <div class="form-title">Hoàn Thành</div></label>
                        <div class="text-center">
                        <?php
                            echo $this->formButton($_formObj->get('SaveFieldset')->get('save'));
                        ?>
                        </div>
                    </div>
                    </div>
                </div>        
            </div>
    </div>
</div>
</div>
</form> <script type="text/javascript"><!--
    var filter_row = <?php echo $filter_row; ?>;

    function addFilterRow() {
        html  = '<tr id="filter-row' + filter_row + '">';   
        html += '  <td><input type="hidden" name="filter[' + filter_row + '][filter_id]" value="" />';
        html += '<input type="text" name="filter[' + filter_row + '][name]" value="" placeholder="Filter Name" class="form-control" />';
            html += '  </td>';
        html += '  <td class="text-right"><input type="text" name="filter[' + filter_row + '][sort_order]" value="" placeholder="Sort Order" id="input-sort-order" class="form-control" /></td>';
        html += '  <td class="text-left"><button type="button" onclick="$(\'#filter-row' + filter_row + '\').remove();" data-toggle="tooltip" title="Remove" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>';
        html += '</tr>';    
        
        $('#filter tbody').append(html);
        
        filter_row++;
    }
    //--></script>