<?php
$_formObj   = $this->_formObj;
$arrForm = array(
    array(
        'Start_Layout' => '<div class="col-lg-8 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                   array(
                        'Content_Box' => '<div class="form-group">
                                '.$this->formLabel($_formObj->get('name')).'
                                <div class="controls">
                                 '.$this->formInput($_formObj->get('name')).'
                                </div>
                          </div>',
                    ),
                    array(
                        'Content_Box' => '<div class="form-group">
                            '.$this->formLabel($_formObj->get('General')->get('describe')).'
                            <div class="controls">
                                  '.$this->formTextarea($_formObj->get('General')->get('describe')).'
                              </div>
                          </div>',
                    ),
                    array(
                        'Content_Box' => '<div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label strong" for="Author">Tác giả</label>
                                        <div class="controls">
                                        '.$this->formSelect($_formObj->get('Author')).'
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="control-label strong" for="BlogId">Danh mục</label>
                                        <div class="controls">
                                           '.$this->formSelect($_formObj->get('collections')).'
                                        </div>
                                    </div>
                                </div>
                            </div>',
                    ),
                ),
                'End_Widget'     => '</div></div>',
            ),
           
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        'Content_Box' => '<label class="title-product-main text-no-bold mb20">Tối ưu SEO</label><p class="mb0">Thiết lập các thẻ mô tả giúp khách hàng dễ dàng tìm thấy sản phẩm trên công cụ tìm kiếm như Google.</p><div class="pd-t-20 border-top-title-main" data-bind="visible:IsShowSEOSetting"><div class="pd-t-20 ps-relative"><div class="form-group">
                                            <label for="meta_title">Tiêu đề trang</label>
                                            '.$this->formInput($_formObj->get('General')->get('meta_title')).'
                                        </div><div class="form-group">
                                            <label for="meta_description">Mô tả trang</label>
                                            '.$this->formTextarea($_formObj->get('General')->get('meta_description')).'
                                        </div><div class="form-group">
                                           
                                        <label for="alias">Đường dẫn</label>
                                        <a href="https://docs.haravan.com/blogs/co-ban/1000019770-handle" target="_blank">
                                            <i class="hover-tooltip glyphicon glyphicon-question-sign note"></i>
                                        </a>
                                            <div class="input-group">
                                        <span class="input-group-addon drop-price-addon border-color-input-group" data-bind="text: ProductDetail().PrefixUrl">http://vndgroup-zf2/products/</span>
                                       '.$this->formInput($_formObj->get('General')->get('alias')).'
                                    </div>
                                        </div></div></div>',
                    ),
                ),
                'End_Widget'     => '</div></div>',
            ),
        ),
        'End_Layout' => '</div>'
    ),
   
    array(
        'Start_Layout' => '<div class="col-lg-4 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        'Content_Box' => '<h4>Trạng thái</h4>
                                            <p class="text-muted">Cho phép thiết lập thời gian sản phẩm được hiển thị.</p><div class="form-group">
                                    <div class="radio">'.$this->formRadio($_formObj->get('General')->get('status')).'</div>
                                    <div class="radio"></div>
                            </div>',
                    ),
                ),
                'End_Widget'     => '</div></div>',
            ),
            array(
                'Start_Widget' => '<div class="widget"><div class="widget-body"><label class="title-product-main text-no-bold block-display text-center mb20">Hoàn thiện đăng sản phẩm</label>',
                'Content_Widget' => array(
                    array(
                        'Content_Box' => '<div class="pd-t-20 border-top-title-main text-center">'.$this->formButton($_formObj->get('General')->get('save_and_new')).' '.$this->formButton($_formObj->get('General')->get('save')).'</div>',
                    ),
                ),
                'End_Widget' => '</div></div>'
            ),
        ),
        'End_Layout' => '</div>'
    ),
);
$FormObj = new \VND\ViewHelper\FormView($arrForm,array('type'=>'Admin'));

?>
<div class="page-body">
<?php
    echo $FormObj->xHtml;
?>

</div>