
<style type="text/css">
.tabbableVND .tab-content {
    box-shadow: none;
}.tabs-vnd {
    border-bottom: 1px solid #14a1d4;
}.tabs-vnd li.active {
    border-radius: 2px 2px 0 0;
    background: #14a1d4;
}
.tabs-vnd li {
    float: left;
}.tabs-vnd li.active a {
    color: #fff;
}

.tabs-vnd li a {
    line-height: 28px;
    padding: 0 10px;
}.tabs-vnd li a:focus, .tabs-vnd li a:hover {
    text-decoration: none;
    background: none !important;
}
.infoCustomer li {
    list-style: none;
    border: 1px solid #ddd;
    padding: 5px;
}.infoCustomer a.txtBlue {
    margin: 0px 10px 0 10px;
}span.veaM {
    margin-left: 10px;
}
.infoCustomer a{
    padding:0;
}.infoCustomer {
    padding: 10px 0;
}.infoCustomer a.icon.del i {
    background: #2dc3e8;
    color: #fff;
    padding: 3px;
}.list-search-data a.block-display{
    line-height: 30px;
}.box-search-advance a{
    text-decoration: none;
}
.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #ddd;
    vertical-align: middle;
}ul.shippingClass {
    padding: 0 1px;
    list-style: none;
}
ul.innerHtml {
  
}ul.innerHtml li {
    overflow: hidden;
    border-bottom: 1px solid #ddd;
    padding: 6px;
    list-style: none;
}
.box-search-advance {
position: relative;
z-index: 3;
}
.inline_block {
    display: inline-block;
}
.box-search-advance .panel-default {
    position: absolute;
    top: 100%;
    left: 0;
    -moz-transform: translateY(0) scale(0);
    -ms-transform: translateY(0) scale(0);
    -o-transform: translateY(0) scale(0);
    -webkit-transform: translateY(0) scale(0);
    transform: translateY(0) scale(0);
    max-width: 100%;
    margin-top: 5px;
    background-color: rgba(255,255,255,0.98);
    border-radius: 3px;
    opacity: 0;
    -webkit-transition: -webkit-transform 0.3s ease,opacity 0.3s ease;
    -moz-transition: all 0.3s ease,opacity 0.3s ease;
    -o-transition: all 0.3s ease,opacity 0.3s ease;
    transition: all 0.3s ease,opacity 0.3s ease;
    width: 100%;
    -moz-transform-origin: 50% -20px;
    -ms-transform-origin: 50% -20px;
    -o-transform-origin: 50% -20px;
    -webkit-transform-origin: 50% -20px;
    transform-origin: 50% -20px;
}

    .box-search-advance .panel-default .panel-body {
        max-height: 300px;
        overflow-y: auto;
        padding-top: 0;
    }

    .box-search-advance .panel-default.active {
        -webkit-transform: translateY(0) scale(1);
        -moz-transform: translateY(0) scale(1);
        -ms-transform: translateY(0) scale(1);
        -o-transform: translateY(0) scale(1);
        transform: translateY(0) scale(1);
        opacity: 1;
        z-index: 1;
    }

        .box-search-advance .panel-default.active:before {
            position: absolute;
            top: -7px;
            left: 0;
            right: 0;
            margin: auto;
            display: inline-block;
            border-right: 7px solid transparent;
            border-bottom: 7px solid #F3FAFF;
            border-left: 7px solid transparent;
            border-bottom-color: rgba(175, 166, 166, 0.2);
            content: '';
            width: 3px;
        }

        .box-search-advance .panel-default.active:after {
            position: absolute;
            left: 0;
            right: 0;
            top: -6px;
            margin: auto;
            display: inline-block;
            border-right: 6px solid transparent;
            border-bottom: 6px solid #ffffff;
            border-left: 6px solid transparent;
            content: '';
            width: 3px;
        }

    .box-search-advance .panel-default .list-search-data > ul > li {
        padding: 10px 13px;
        cursor: pointer;
        border-top: 1px solid #EBEEF0;
        list-style: none
    }
    .box-search-advance .panel-default .list-search-data > ul > li:first-child {
        border-top: 0;
    }

.findcustomer .list-search-data > ul > li {
padding: 5px 13px !important;
}

.findcustomer .box-search-advance .panel-default .list-search-data > ul > li.active, .findcustomer .box-search-advance .panel-default .list-search-data > ul > li:hover {
background: #479CCF;
}

.findcustomer .box-search-advance .panel-default .list-search-data > ul > li.active *, .findcustomer .box-search-advance .panel-default .list-search-data > ul > li:hover * {
    color: #fff !important;
}

.box-search-advance .panel-default .list-search-data > ul > li ul {
padding-left: 40px;
}

.box-search-advance .panel-default .list-search-data > ul > li ul li {
    padding: 7px 10px;
}

    .box-search-advance .panel-default .list-search-data > ul > li ul li:hover {
        background: #EFF9FD;
    }

.box-search-advance .panel-default .list-search-data .wrap-img, .box-search-advance .panel-default .list-search-data .img-empty {
min-height: 32px;
min-width: 32px;
height: 30px;
width: 30px;
margin-top: 2px;
}
.vertical-align-t{
    vertical-align: top
}
.box-search-advance .panel-default .list-search-data .img-empty {
padding: 6px 2px;
}

.box-search-advance .panel-default{    border: solid 1px #dee5eb !important;}
.box-search-advance .panel-footer{overflow:hidden;}
.box-search-advance .panel-default .list-search-data .wrap-img img {
min-height: 30px;
min-height: 30px;
height: 30px;
width: 30px;
}

.box-search-advance-head {
padding: 10px 15px;
border-bottom: 1px solid #E0E6EC;
margin-left: -15px;
margin-right: -15px;
cursor: pointer;
}

.box-search-advance-head:hover {
    background: #EFF9FD;
}

.findcustomer .box-search-advance-head:hover {
background: #479CCF;
color: #fff;
}


</style>
<?php
$xShipping = '<div class="row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label class="control-label strong" for="lastname">Họ</label>
                            '.$this->formInput($_formObj->get('lastname')).'
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="form-group">
                          <label class="control-label strong" for="FirstName">Tên</label>
                            '.$this->formInput($_formObj->get('firstname')).'
                            
                        </div>
                      </div>
                    </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label strong" for="Company">Công ty</label>
                              <input class="form-control valid" id="Company" name="Company" placeholder="Nhập Công ty" type="text" value="Hà Nội" >
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label strong" for="Phone">Số điện thoại</label>
                               '.$this->formInput($_formObj->get('telephone')).'
                          
                        </div>
                    </div>
                </div>
                <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label strong" for="Address1">Địa chỉ</label>
                          '.$this->formInput($_formObj->get('address')).'
                    </div>
                </div>
            </div>
            <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label strong" for="CountryId">Quốc gia</label>
                            <div class="controls">
                                    <select bind="country_id" bind-event-change="changeCountry()"
                                        class="form-control valid" id="CountryId" name="CountryId"
                                        style="width: 100%;" ><option value="1">United
                                            States</option>
                                        <option value="80">United Kingdom</option>
                                        <option value="81">United States minor outlying islands</option>
                                        <option value="82">Uruguay</option>
                                        <option value="83">Uzbekistan</option>
                                        <option value="84">Venezuela</option>
                                        <option value="85">Serbia</option>
                                        <option value="86">Afghanistan</option>
                                        <option value="87">Albania</option>
                                        <option value="88">Algeria</option>
                                        <option value="89">American Samoa</option>
                                        <option value="221">Tonga</option>
                                        <option value="222">Trinidad and Tobago</option>
                                        <option value="223">Tunisia</option>
                                        <option value="224">Turkmenistan</option>
                                        <option value="225">Turks and Caicos Islands</option>
                                        <option value="226">Tuvalu</option>
                                        <option value="227">Uganda</option>
                                        <option value="228">Vanuatu</option>
                                        <option value="229">Vatican City State (Holy See)</option>
                                        <option selected="selected" value="230">Việt Nam</option>
                                        <option value="231">Virgin Islands (British)</option>
                                        <option value="232">Virgin Islands (U.S.)</option>
                                        <option value="233">Wallis and Futuna Islands</option>
                                        <option value="234">Western Sahara</option>
                                        <option value="235">Yemen</option>
                                        <option value="236">Zambia</option>
                                        <option value="237">Zimbabwe</option>
                                    </select>
                                    
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label strong" for="Zip">Postal / Zip Code</label>
                               '.$this->formInput($_formObj->get('address_zip')).'
                                
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-6">
                        <label>Tỉnh/Thành phố</label>
                        <select name="shipping_city" class="form-control"><option value="1">Vĩnh Phúc</option>
                <option value="2">Hồ Chí Minh</option></select>
                    </div>
                    <div class="form-group col-sm-6">
                        <label>Quận/Huyện</label><select name="shipping_district" class="form-control"><option value="1">Sóc sơn</option>
                <option value="2">Đông Anh</option></select>
                    </div>
                </div>
                <div class="clear"></div>       ';
$xPay = '<div class="row">
            <div class="form-group col-sm-6">
                <label>Họ</label>
                 '.$this->formInput($_formObj->get('payment_lastname')).'
            </div>
            <div class="form-group col-sm-6">
                <label>Tên</label>'.$this->formInput($_formObj->get('payment_firstname')).'
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Số điện thoại</label>'.$this->formInput($_formObj->get('payment_telephone')).'
            </div>

            <div class="form-group col-sm-6">
                <label>Địa chỉ</label>
                '.$this->formInput($_formObj->get('payment_address')).'
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                <label>Tỉnh/Thành phố</label>
                '.$this->formSelect($_formObj->get('payment_city')).'
            </div>
            <div class="form-group col-sm-6">
                <label>Quận/Huyện</label>'.$this->formSelect($_formObj->get('payment_district')).'
            </div>
        </div>
        <div class="clear"></div>';
$xAddCustomer = '<div class="row">
    <div class="form-group col-sm-6">
        <label>Họ</label>
         '.$this->formInput($_formObj->get('lastname')).'
    </div>
    <div class="form-group col-sm-6">
        <label>Tên</label>'.$this->formInput($_formObj->get('firstname')).'
    </div>
</div>

<div class="row">
    <div class="form-group col-sm-12">
        <label>Email</label>'.$this->formInput($_formObj->get('email')).'
    </div>
    <div class="form-group col-sm-12 ">
       <div class="checkbox"><label class="radio">'.$this->formCheckbox($_formObj->get('accepts_marketing')).' Khách hàng chấp nhận tiếp thị</label></div>
    </div>
</div>
<div class="row">
    <hr>
    <div class="form-group col-sm-12">
        <label>Địa chỉ</label>
        '.$this->formInput($_formObj->get('address')).'
    </div>
    <div class="form-group col-sm-6">
        <label>Số điện thoại</label>'.$this->formInput($_formObj->get('telephone')).'
    </div>
    <div class="col-sm-6">
      <div class="form-group">
      <label>Postal / Zip Code</label><input type="text" name="address_zip" class="form-control" value="">
    </div>
  </div>
    
</div>
<div class="row">
    <div class="form-group col-sm-6">
        <label>Tỉnh/Thành phố</label>
        '.$this->formSelect($_formObj->get('city')).'
    </div>
    <div class="form-group col-sm-6">
        <label>Quận/Huyện</label>'.$this->formSelect($_formObj->get('district')).'
    </div>
</div>
<div class="clear"></div>';
$_formObj   = $this->_formObj;
$xSearch = '<div class="findcustomer">
    <div class="box-search-advance customer" data-bind="css:ObjectType()">
        <div>
            <input type="text" class="form-control textbox-advancesearch" id="searchDrop" placeholder="Tìm hoặc tạo khách hàng mới">
        </div>
        <div class="panel panel-default">
            <div class="panel-body" style="width: 99%;">
                <div class="box-search-advance-head"><a href="javascript:void(0);" data-toggle="modal" data-target="#addCustomer">
                    <img width="30" src="//hstatic.net/0/0/global/design/imgs/next-create-customer.svg">
                    <span class="inline_block"  >Tạo mới khách hàng</span></a>
                </div>
                <div class="list-search-data">
                    
                    <div class="search-loading hidden">Đang tìm kiếm..</div>
                </div>
                <!--/ko-->
            </div>

            <div class="panel-footer">
                <div class="btn-group pull-right" >
    <!-- ko with: Page -->
    <button type="button" class="btn btn-default disable"><i class="fa fa-chevron-left"></i></button>
    <button  type="button" class="btn btn-default disable"><i class="fa fa-chevron-right"></i></button>
    <!-- /ko -->
</div>
                <div class="clear"></div>
            </div>
        </div>

    </div>

    </div>
<div class="infoCustomer"></div>';
$xSearchPrd = '<div class="findproduct">
    <div class="box-search-advance product" data-bind="css:ObjectType()">
        <div>
            <input type="text" class="form-control" id="searchPrd" placeholder="Nhập từ khóa tìm kiếm ...(Tên sản phẩm, Tên variant, SKU, Tag)">
        </div>
        <div class="panel panel-default">
            <div class="panel-body" style="width: 99%;">
                <div class="list-search-data-prd">
                    <div class="search-loading hidden">Đang tìm kiếm..</div>
                </div>
            </div>

            <div class="panel-footer">
                <div class="btn-group pull-right">
    <!-- ko with: Page -->
    <button type="button" class="btn btn-default disable"><i class="fa fa-chevron-left"></i></button>
    <button type="button" class="btn btn-default disable"><i class="fa fa-chevron-right"></i></button>
    <!-- /ko -->
</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    </div>';
$arrForm = array(
    array(
        'Start_Layout' => '<div class="col-lg-8 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body"><label class="title-product-main text-no-bold mb20">Chi tiết đơn hàng</label><p class="mb0">Gõ tên sản phẩm hoặc mã sản phẩm vào ô bên dưới để tìm kiếm sản phẩm.</p>',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        //'.$this->formInput($_formObj->get('key_search')).'
                        'Content_Box' => '<div class="table-wrapper p-none margin-bottom-10" id="showLineItem">
				                                <div class="table-responsive">
				                                    <table class="table" id="listItem">
				                                        <tbody>
				                                        </tbody>
				                                    </table>
				                                </div>
                							</div><div class="form-group no-margin-bottom" id="products">
                                            <span class="input-icon">
                							'.$xSearchPrd.'
                							<i class="glyphicon glyphicon-search blue"></i></span>
                							<div id="showProduct"></div>
                                    </div>
                							',
                    ),
                    // BOx List Item
                    array(
                        'Content_Box' => '<div class="table-wrapper p-none mb20">
                                <div class="table-responsive">
                                    <table class="table" id="listItem">
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>',
                    ),
                    // Box Detai
                    array(
                        'Content_Box' => '<label class="title-product-main text-no-bold mb20">Chi tiết đơn hàng</label><div class="clearfix"><div class="form-group">
                                            <label class="text-no-bold"></label>
                                            <div class="form-group col-sm-6 pd-0 "><div class="form-title">Ghi chú</div><span class="input-icon icon-right"><textarea name="note" class="form-control" rows="4"></textarea><i class="glyphicon glyphicon-briefcase darkorange"></i></span></div>
                                        </div><div class="form-group">
                                            <label class="text-no-bold"></label>
                                            <div class="col-sm-6">
                                    <div class="table-responsive">
                                        <table class="table table-border-none text-right">
                                            <tbody><tr>
                                                <td>Tổng giá trị sản phẩm</td>
                                                <td id="TotalItemOrder">0 ₫</td>
                                            </tr>
                                            <tr>
                                                <td class="p-xs">
                                                <a onclick="Order.Information.addDiscount()" class="hover-underline" data-toggle="modal" data-target="#addDiscount" name="status-pay"><i class="fa fa-plus-circle"></i> Thêm khuyến mãi</a>
                                                </td>
                                                <td id="DiscountOrder">0 ₫</td>
                                            </tr>
                                            <tr>
                                                <td class="p-xs" ><a href="javascript:void(0);" data-toggle="modal" data-target="#addShipping" class="hover-underline"><i class="fa fa-plus-circle"></i> Thêm phí vận chuyển</a>
                                                <p id="Shipping"></p>
                                                </td>
                                                <td id="ShippingValue">0 ₫</td>
                                            </tr>
                                            <tr>
                                                <td class="p-xs">Số tiền phải thanh toán</td>
                                                <td data-bind="textMoneyWithSymbol: GrandTotal">0 ₫</td>
                                            </tr>
                                        </tbody></table>
                                    </div>

                                </div>
                                        </div></div>',
                    ),
                    // Box Confirm
                   
                ),
                'End_Widget'     => '</div></div>',
            ),
            
            
        ),
        'End_Layout' => '</div>'
    ),
    // Layout col-sm-4
    array(
        'Start_Layout' => '<div class="col-lg-4 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget' => '<div class="tabbableVND">',
                'Content_Widget'  => array(
                    array(
                        'Content_Box' => ' <ul class="nav tabs-vnd" id="myTab">
                                            <li class="active"><a data-toggle="tab" href="#home">Thông tin</a></li>
                                            <li class="tab-red"><a data-toggle="tab" href="#profile">Mở rộng</a></li>
                                            </ul>

                                            <div class="tab-content">
                                                <div id="home" class="tab-pane in active">
                                                    '.$xSearch.'
                                                </div>

                                                <div id="profile" class="tab-pane">
                                                <div class="form-title"><span class="text-upper">Thông tin giao hàng </span>
                                                <a onclick="Order.updateShipping()" class="pull-right">Sửa</a> </div> 
                                                <ul class="shippingClass">
                                                
                                                </ul>
                                                <div class="form-title"><span class="text-upper">Thông tin thanh toán </span>
                                                <a data-toggle="modal" data-target="#shipping_options"  class="pull-right">Sửa</a> </div> 
                                                <ul class="shippingClass">
                                                <li><strong>Họ đệm</strong> : Nguyễn Văn</li> 
                                                <li><strong>Tên</strong> : Tuấn</li> 
                                                <li><strong>Số điện thoại</strong> : 01672.050.838</li> 
                                                <li><strong>Tỉnh/Thành phố</strong> : Hà Nội</li> 
                                                <li><strong>Quận huyện</strong> : Mê Linh</li> 
                                                <li><strong>Quốc Gia</strong> : Việt Nam</li> 
                                                </ul>
                                                <div class="form-group border-top-title-main">
                                                    <label class="margin-top-10"><strong>Ngày tạo</strong></label>
                                                      <span class="input-icon icon-right">
                                                        '.$this->formInput($_formObj->get('date_created')).'
                                                        <i class="fa fa-calendar"></i>
                                                      </span>
                                                </div>
                                                </div>

                                                
                                            </div>',
                    )
                    
                ),
                'End_Widget'   => '</div>'
            ),
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        'Content_Box' => '<div class="clearfix text-center">
                                            <span class="text-upper "><strong>Xác nhận thanh toán và tạo đơn hàng</strong></span>
                                            <div class="rps-float-none  text-center margin-top-20">
                                              <button type="submit" name="status-pay" class="btn btn-blue" value="">Đã thanh toán</button> <button type="button" name="pay-later" class="btn btn-blue" value="">Thanh toán sau</button></div>
                                          </div>',
                    ),
                ),
                'End_Widget'     => '</div></div>',
            ),
        ),
        'End_Layout'   => '</div>'
    )
);
$FormObj = new \VND\ViewHelper\FormView($arrForm,array('type'=>'Admin'));
?>
<!-- Popup ADD Discount order -->
<div class="modal fade" id="addDiscount">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Thêm hoặc sửa thông tin giao hàng</h4>
              </div>
            <div class="modal-body">
              <div class="form-group">
                <label>Giảm giá đơn hàng này theo </label>
                <div class="input-group">
                  <div class="input-group-btn">
                    <!--ko if :IsAmount() == true-->
                    <button value="fixed_amount" class="btn active btn-default btn-active">₫</button>
                    <button value="percentage" class="btn ac btn-default btn-active" >
                      %
                    </button>
                    <!--/ko-->
                    <!--ko if :IsPercentage() == true--><!--/ko-->
                  </div>
                  <!--ko if :IsAmount() == true-->
                  <div class="input-group width100">
                    <input type="number" class="form-control border-none-radius border-none-r width-input-discount" id="valueDiscount"  >
                    <span class="input-group-addon input-text-currency" id="textTypeDiscount">₫</span>
                  </div>
                  <!--/ko--><!--ko if :IsPercentage() == true--><!--/ko-->
                </div>
              </div>
              <div class="form-group">
                <label>Lý do</label>
                <input placeholder="Giảm giá sản phẩm, khách hàng thân thiết" class="form-control" >
              </div>
            </div>
            <div class="modal-footer">
              <div class="pull-left">
                <a class="btn btn btn-default" data-toggle="modal" data-dismiss="modal">Đóng</a>
              </div>
              <div class="pull-right">
                <button type="button" id="submitDiscount" onclick="Order.Information.addDiscount()" class="btn btn-primary">Thêm khuyến mãi</button>
              </div>
            </div>
            </div>
        </div>
</div>
<!-- Popup ADD Shipping order -->
<div class="modal fade" id="addShipping">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Thêm hoặc sửa thông tin giao hàng</h4>
              </div>
            <div class="modal-body">
              <!--ko if : !CustomerId()-->
              <div class="alert-warning alert">
                <label class="block-display mb10">Làm sao để chọn phí vận chuyển đã cấu hình ? </label>
                <p>Hãy thêm thông tin khách hàng với địa chỉ giao hàng đầy đủ để thấy các mức phí vận chuyển đã cấu hình.</p>
              </div>
              <!--/ko-->
              <div data-bind="foreach:ShippingList"></div>
              <div class="form-group">
                <div class='radio'>
                    <label class="radio">
                      <!-- ko if: (value == undefined || value == null) && (checkedValue != undefined && checkedValue != null) --><!-- /ko -->   
                      <!-- ko ifnot: (value == undefined || value == null) && (checkedValue != undefined && checkedValue != null) -->
                      <input type="radio" class=" hrv-radio" name="shipping_method" value="free-shipping" id="">
                      <!-- /ko -->
                      Miễn phí vận chuyển</label>
                </div>
              </div>
              <div class="form-group">
                <div class='radio'>
                    <label class="radio">
                <!-- ko if: (value == undefined || value == null) && (checkedValue != undefined && checkedValue != null) --><!-- /ko -->   
                <!-- ko ifnot: (value == undefined || value == null) && (checkedValue != undefined && checkedValue != null) -->
                    <input type="radio" class=" hrv-radio" value="custom" name="shipping_method">Tùy chỉnh</label>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-7 form-group mb0"><input type="text" class="form-control" placeholder="Tên phí vận chuyển" id="ShippingMethodName"></div>
                <div class="col-sm-5 form-group mb0"><input type="text" class="form-control"  id="OrderShippingFee"></div>
              </div>
            </div>
            <div class="modal-footer">
              <div class="pull-left">
                <a class="btn btn btn-default" data-toggle="modal" data-dismiss="modal">Đóng</a>
              </div>
              <div class="pull-right">
                <button type="button" class="btn btn-primary" onclick="Order.Information.AddShipping()" disabled>Cập nhật</button>
              </div>
            </div>
            </div>
        </div>
</div>
<!-- Popup ADD Shipping order -->
<div class="modal fade" id="addCustomer">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Thêm hoặc sửa thông tin giao hàng</h4>
              </div>
            <div class="modal-body">
              <!--ko if : !CustomerId()-->
              <form method="POST" action="/admin/customers/QuickAdd/">
              <?php echo $xAddCustomer; ?>
              </form>
            </div>
            <div class="modal-footer">
              <div class="pull-left">
                <a class="btn btn btn-default" data-toggle="modal" data-dismiss="modal">Đóng</a>
              </div>
              <div class="pull-right">
                <button type="button" class="btn btn-primary">Lưu</button>
              </div>
            </div>
            </div>
        </div>
</div>
<!-- SHIPPING OPTION-->

<!-- Modal -->
<form method="POST" id="Order" action="">
<input type="hidden" name="TypeDiscount" value="">
<input type="hidden" name="DiscountValue" value="">
<input type="hidden" name="ShippingMethodName" value="">
<input type="hidden" name="OrderShippingFee" value="">
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
            <?php echo $FormObj->xHtml; ?>
            
            </div>
        </div>
    </div>
</div>
<div id="contentShipping">
<div class="modal fade" id="UpdateShipping">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Thêm hoặc sửa thông tin giao hàng</h4>
              </div>
            <div class="modal-body">
                <div class="bootbox-body">
                   <?php echo $xShipping; ?>
                </div>
            
            </div>
            <div class="modal-footer">
               <div class="modal-footer">
              <div class="pull-left">
                <a class="btn btn btn-default" data-toggle="modal" data-dismiss="modal">Đóng</a>
              </div>
              <div class="pull-right">
                <button type="button" onclick="Order.updateShipping02()" class="btn btn-primary">Lưu</button>
              </div>
            </div>
            </div>
            </div>
        </div>
</div>
</div>
<!-- PAY OPTION-->
<div class="modal fade" id="payment_options">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Thêm hoặc sửa thông tin thanh toán</h4>
              </div>
            <div class="modal-body">
                <div class="bootbox-body">
                   <?php echo $xPay; ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Lưu</button>
            </div>
            </div>
        </div>
</div>
</form>