<?php
$_formObj   = $this->_formObj;
$arrForm = array(
    array(
        'Start_Layout' => '<div class="col-lg-8 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        'Content_Box' => '<div class="form-group">
                                            '.$this->formLabel($_formObj->get('name')).'
                                            <div class="controls">
                                             '.$this->formInput($_formObj->get('name')).'
                                            </div>
                                      </div>',
                    ),
                    array(
                        'Content_Box' => '<div class="row">
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        '.$this->formLabel($_formObj->get('attribute_group_id')).$this->formSelect($_formObj->get('attribute_group_id')).'
                                                    </div>
                                                </div>
                                                 <div class="col-sm-3">
                                                    <div class="form-group">
                                                        '.$this->formLabel($_formObj->get('sort_order')).$this->formInput($_formObj->get('sort_order')).'
                                                    </div>

                                                </div>
                                        </div>',
                    ),
                ),
                'End_Widget'     => '</div></div>',
            ),
        ),
        'End_Layout' => '</div>'
    ),
    array(
        'Start_Layout' => '<div class="col-lg-4 col-sm-6 col-xs-12">',
        'Widget' => array(
            array(
                'Start_Widget'   => '<div class="widget"><div class="widget-body">',
                'Content_Widget' => array(
                    // Box Search
                    array(
                        'Content_Box' => '<label class="title-product-main text-no-bold block-display text-center "><div class="form-title">Hoàn Thành</div></label><div class="text-center">'.$this->formButton($_formObj->get('save_attribute')).'</div>',
                    ),
                    array(
                        'Content_Box' => $this->formHidden($_formObj->get('attribute_id'))
                    )
                ),
                'End_Widget'     => '</div></div>',
            ),
        ),
        'End_Layout' => '</div>'
    ),
);
$FormObj = new \VND\ViewHelper\FormView($arrForm,array('type'=>'Admin'));
?>
<form method="post" action="">
<div class="page-body">
<div class="row">
    <div class="col-lg-12 col-sm-12 col-xs-12">
        <div class="row">
            <?php
                echo $FormObj->xHtml;
            ?>
        </div>
    </div>
</div>
</div>
</form>
